
max_width = 100
fn_params_layout = "Vertical"
array_width = 60
attr_fn_like_width = 70
chain_width = 60
fn_call_width = 60
struct_lit_width = 10
struct_variant_width = 35

use_small_heuristics = "Max"

use_field_init_shorthand = true
use_try_shorthand = true

match_block_trailing_comma = false

match_arm_leading_pipes = "Preserve"

reorder_imports = true
reorder_modules = true

remove_nested_parens = true
